System Shock 2:
  USE_VSYNC: true
  INJECTION_FRAME_OFFSET_FRACTION: 0.4 # Only applicable if USE_VSYNC == true
  INJECTION_FRAMERATE: 120             # Only applicable if USE_VSYNC == false

  BUTTON_DOWN_TO_KEY_PRESS:
    6  : 9  # SDL_CONTROLLER_BUTTON_START -> VK_TAB
    1  : 32 # SDL_CONTROLLER_BUTTON_B -> VK_SPACE
    2  : 16 # SDL_CONTROLLER_BUTTON_X -> VK_SHIFT
    3  : 79 # SDL_CONTROLLER_BUTTON_Y -> O
    4  : 77 # SDL_CONTROLLER_BUTTON_BACK -> m
    11 : 76 # SDL_CONTROLLER_BUTTON_DPAD_UP -> l
    12 : 85 # SDL_CONTROLLER_BUTTON_DPAD_DOWN -> u
    13 : 72 # SDL_CONTROLLER_BUTTON_DPAD_LEFT -> h
    14 : 73 # SDL_CONTROLLER_BUTTON_DPAD_RIGHT -> i
    100: 82 # SDL_CONTROLLER_TRIGGER_LEFT -> r
  BUTTON_DOWN_TO_KEY_DOWN: {}
  BUTTON_UP_TO_KEY_PRESS:
    4  : 9 # SDL_CONTROLLER_BUTTON_BACK -> VK_TAB
  BUTTON_UP_TO_KEY_UP: {}
  BUTTON_DOWN_TO_MOUSE_EVENT:
    0  : 3 # SDL_CONTROLLER_BUTTON_A -> MOUSE_RIGHT_PRESS
    101: 1 # SDL_CONTROLLER_TRIGGER_RIGHT -> MOUSE_LEFT_DOWN
    9  : 7 # SDL_CONTROLLER_BUTTON_LEFTSHOULDER -> MOUSE_WHEEL_UP
    10 : 6 # SDL_CONTROLLER_BUTTON_RIGHTSHOULDER -> MOUSE_WHEEL_DOWN
  BUTTON_UP_TO_MOUSE_EVENT:
    101: 2 # SDL_CONTROLLER_TRIGGER_RIGHT -> MOUSE_LEFT_UP

  LOOK_STICK: 1 # -1: Not used, 0: Left stick, 1: Right stick

  LEFT_STICK_KEY_LEFT : 65 # A
  LEFT_STICK_KEY_RIGHT: 68 # D
  LEFT_STICK_KEY_UP   : 87 # W
  LEFT_STICK_KEY_DOWN : 83 # S

  RIGHT_STICK_KEY_LEFT : 0
  RIGHT_STICK_KEY_RIGHT: 0
  RIGHT_STICK_KEY_UP   : 0
  RIGHT_STICK_KEY_DOWN : 0

  MOVE_SPEED_MIN_AXIS_VALUE: 5000
  MOVE_SPEED_MAX_AXIS_VALUE: 32767
  MOVE_SPEED_DUTY_CYCLE_MIN: 0.0

  LOOK_SPEED_MIN_AXIS_VALUE: 5000
  LOOK_SPEED_MAX_AXIS_VALUE: 32767
  LOOK_SPEED_MIN_X         : 0
  LOOK_SPEED_MAX_X         : 1000
  LOOK_SPEED_MIN_Y         : 0
  LOOK_SPEED_MAX_Y         : 1000

  TRIGGER_DEPTH: 16384
